using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Clain.DesignTime.Common;

namespace Clain.DesignTime.Blazor
{
    /// <summary>
    /// Incremental source generator that injects data-clain-src attributes into Blazor components.
    /// Analyzes .razor files and generates partial classes that add source location metadata
    /// to HTML elements for click-to-source navigation in design-time environments.
    ///
    /// Phase 1: Minimal implementation for single div element in simple components.
    /// </summary>
    [Generator]
    public class ClainBlazorSourceGenerator : IIncrementalGenerator
    {
        private const string GeneratorName = "ClainBlazorSourceGenerator";
        private const string GeneratorVersion = "0.1.0";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
#if DEBUG || CLAIN_DESIGN
            // Register a source output that will be invoked for each compilation
            context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
                "ClainBlazorSourceGenerator.g.cs",
                SourceText.From(GetGeneratorAttributeSource(), Encoding.UTF8)));

            // Get all additional files (.razor files)
            var razorFiles = context.AdditionalTextsProvider
                .Where(file => file.Path.EndsWith(".razor"));

            // Combine with compilation
            var compilationAndFiles = context.CompilationProvider
                .Combine(razorFiles.Collect());

            // Register source output
            context.RegisterSourceOutput(compilationAndFiles, (spc, source) =>
            {
                GenerateSourceForRazorFiles(spc, source.Left, source.Right);
            });
#endif
        }

        private void GenerateSourceForRazorFiles(
            SourceProductionContext context,
            Compilation compilation,
            ImmutableArray<AdditionalText> razorFiles)
        {
            foreach (var razorFile in razorFiles)
            {
                // Phase 1: Minimal implementation - detect single <div> and generate attribute
                ProcessRazorFile(context, razorFile, compilation);
            }
        }

        private void ProcessRazorFile(
            SourceProductionContext context,
            AdditionalText razorFile,
            Compilation compilation)
        {
            // Read the .razor file content
            var sourceText = razorFile.GetText(context.CancellationToken);
            if (sourceText == null)
            {
                return;
            }

            var content = sourceText.ToString();

            // Phase 1: Simple detection of <div> elements
            // TODO: Use proper Razor syntax tree parsing in later phases
            if (!content.Contains("<div"))
            {
                return; // No divs to process
            }

            // Extract component name from file path
            var fileName = System.IO.Path.GetFileNameWithoutExtension(razorFile.Path);
            var componentNamespace = GetComponentNamespace(compilation, fileName);

            // Generate source with attribute injection
            var generatedSource = GenerateComponentSource(fileName, componentNamespace, razorFile.Path, content);

            context.AddSource($"{fileName}.Clain.g.cs", SourceText.From(generatedSource, Encoding.UTF8));
        }

        private string GetComponentNamespace(Compilation compilation, string componentName)
        {
            // Try to find the component's namespace from the compilation
            var componentSymbol = compilation.GetSymbolsWithName(componentName).FirstOrDefault();
            if (componentSymbol != null)
            {
                return componentSymbol.ContainingNamespace.ToDisplayString();
            }

            // Fallback to root namespace
            return compilation.AssemblyName ?? "App";
        }

        private string GenerateComponentSource(string componentName, string namespaceName, string filePath, string razorContent)
        {
            // Phase 1: Generate a comment placeholder that documents the approach
            // Full implementation will inject BuildRenderTree modifications

            var normalizedPath = PathUtilities.NormalizePath(filePath);

            return $@"// <auto-generated>
// Generated by {GeneratorName} v{GeneratorVersion}
// Source: {normalizedPath}
// </auto-generated>

#if DEBUG || CLAIN_DESIGN
namespace {namespaceName}
{{
    /// <summary>
    /// Clain design-time source mapping for {componentName}
    /// Phase 1: Placeholder for BuildRenderTree attribute injection
    /// </summary>
    public partial class {componentName}
    {{
        // TODO: Implement BuildRenderTree wrapper that injects data-clain-src attributes
        // for all HTML elements in this component

        // Example target transformation:
        // Original: builder.OpenElement(0, ""div"");
        // Modified: builder.OpenElement(0, ""div"");
        //           builder.AddAttribute(1, ""data-clain-src"", ""{normalizedPath}:line:char"");
    }}
}}
#endif
";
        }

        private string GetGeneratorAttributeSource()
        {
            return $@"// <auto-generated/>
namespace Clain.DesignTime.Blazor
{{
    [System.CodeDom.Compiler.GeneratedCode(""{GeneratorName}"", ""{GeneratorVersion}"")]
    internal class GeneratorMetadata
    {{
        public const string Name = ""{GeneratorName}"";
        public const string Version = ""{GeneratorVersion}"";
    }}
}}
";
        }
    }
}
